[package]
name = "kira"
version = "0.1.1"
authors = ["Andrew Minnich <aminnich3@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Dynamic audio library for games"
repository = "https://github.com/tesselode/kira"
keywords = ["gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "../readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
benchmarking = []

[dependencies]
claxon = "0.4.3"
cpal = "0.13.1"
indexmap = "1.6.0"
hound = "3.4.0"
lewton = "0.10.1"
minimp3 = "0.5.0"
ringbuf = "0.2.2"
